-- =====================================================================
-- Generated by scripts/seed-figma.ts
-- Generated at: 2026-05-13T14:16:29.307Z
-- Source     : Figma "2026 Web site_dev" (https://www.figma.com/design/dFy4bUmxNmS6WJ6QgwBa4I/)
-- Strategy   : additive only. Aborts on any name collision.
-- How to run : open in DataGrip on prod connection, execute the whole file, inspect,
--              then run COMMIT (or ROLLBACK) by hand. The file does not commit itself.
-- =====================================================================

BEGIN;
SET LOCAL statement_timeout = '60s';

-- Pre-flight guard: abort if any seed name already exists.
DO $$
DECLARE
  v_cohorts_existing  INT;
  v_projects_existing INT;
  v_blogs_existing    INT;
BEGIN
  SELECT count(*) INTO v_cohorts_existing
    FROM cohorts
   WHERE name IN ('9기', '11기', '12기')
     AND "deletedAt" IS NULL;

  SELECT count(*) INTO v_projects_existing
    FROM projects
   WHERE name IN ('FESTIBEE (페스티비)', 'GROWIT (그로잇)', 'MOYORAK (모여락)', '엠쿵', 'POLABO', 'MOZIP', 'Pregen', '명언제과점', 'Fridge Link')
     AND "deletedAt" IS NULL;

  SELECT count(*) INTO v_blogs_existing
    FROM blog_posts
   WHERE title IN ('픽셀을 넘어 공간으로: AI 시대, 디자이너가 XR에 주목해야 하는 이유')
     AND "deletedAt" IS NULL;

  IF v_cohorts_existing > 0 THEN
    RAISE EXCEPTION 'seed aborted: % cohorts already exist with seed names', v_cohorts_existing;
  END IF;

  IF v_projects_existing > 0 THEN
    RAISE EXCEPTION 'seed aborted: % projects already exist with seed names', v_projects_existing;
  END IF;

  IF v_blogs_existing > 0 THEN
    RAISE EXCEPTION 'seed aborted: % blog_posts already exist with seed titles', v_blogs_existing;
  END IF;
END $$;

-- 1. Dummy display cohorts (status=CLOSED; recruit dates are placeholders).
INSERT INTO cohorts (name, "recruitStartAt", "recruitEndAt", status) VALUES
  ('9기', '2023-01-01'::timestamp, '2023-06-30'::timestamp, 'CLOSED'::cohorts_status_enum),
  ('11기', '2024-01-01'::timestamp, '2024-06-30'::timestamp, 'CLOSED'::cohorts_status_enum),
  ('12기', '2024-07-01'::timestamp, '2024-12-31'::timestamp, 'CLOSED'::cohorts_status_enum);

-- 2. Projects (cohortId resolved via name; LATERAL ensures one cohort per row).
INSERT INTO projects ("cohortId", platforms, name, description, "thumbnailUrl")
SELECT
  c.id, ARRAY['IOS']::projects_platforms_enum[], 'FESTIBEE (페스티비)', '언제 열리는지, 누가 나오는지, 무슨 곡을 부르는지, 티켓은 언제 오픈하는지...
궁금한 모든 걸 한 번에 확인할 수 있는 곳 👉 페스티비 🐝', 'https://storage.googleapis.com/ddd-project/projects/thumbnails/59ffc43b-3404-4d39-84a1-4e59c66d0fff.png'
FROM cohorts c WHERE c.name = '12기' AND c."deletedAt" IS NULL
UNION ALL
SELECT
  c.id, ARRAY['WEB']::projects_platforms_enum[], 'GROWIT (그로잇)', '작심삼일? 이제 그만! 목표 달성과 회고를 AI 멘토와 함께 게임처럼 즐기며 꾸준히 성장하세요! ✨', 'https://storage.googleapis.com/ddd-project/projects/thumbnails/24544b7f-17d6-40bc-9ecf-26f1bfab67bd.png'
FROM cohorts c WHERE c.name = '12기' AND c."deletedAt" IS NULL
UNION ALL
SELECT
  c.id, ARRAY['IOS']::projects_platforms_enum[], 'MOYORAK (모여락)', '"오늘 점심 뭐 먹지?" 직장인의 점심 스트레스 이제 그만! 점심메뉴 선정 스트레스', 'https://storage.googleapis.com/ddd-project/projects/thumbnails/ab4d96d2-42e0-4252-a52e-edcfae83ffcb.png'
FROM cohorts c WHERE c.name = '12기' AND c."deletedAt" IS NULL
UNION ALL
SELECT
  c.id, ARRAY['IOS']::projects_platforms_enum[], '엠쿵', 'MBTI 기반으로 취향과 성향이 맞는 사람을 연결하는 커뮤니티앱입니다.', 'https://storage.googleapis.com/ddd-project/projects/thumbnails/0b8baa1d-5e3a-4514-83ee-5f0eebf4e250.png'
FROM cohorts c WHERE c.name = '11기' AND c."deletedAt" IS NULL
UNION ALL
SELECT
  c.id, ARRAY['IOS']::projects_platforms_enum[], 'POLABO', '폴라보는 폴라로이드로 함께한 추억과 일상을 특별하게 만드는 사진 중심 참여형 SNS 서비스입니다', 'https://storage.googleapis.com/ddd-project/projects/thumbnails/f03a3841-c401-4529-9e60-972af9594975.png'
FROM cohorts c WHERE c.name = '11기' AND c."deletedAt" IS NULL
UNION ALL
SELECT
  c.id, ARRAY['IOS']::projects_platforms_enum[], 'MOZIP', 'MOZIP은 IT 직군에게 필요한 공모전 • 해커톤 • IT동아리 관련 공고를 한눈에 확인할 수 있는 앱 서비스입니다.', 'https://storage.googleapis.com/ddd-project/projects/thumbnails/9bec9226-efa4-4860-b070-76ceda059582.png'
FROM cohorts c WHERE c.name = '11기' AND c."deletedAt" IS NULL
UNION ALL
SELECT
  c.id, ARRAY['IOS']::projects_platforms_enum[], 'Pregen', '''스와이프''가 아닌 ''이해''로 연결되는 새로운 인터랙션 경험', 'https://storage.googleapis.com/ddd-project/projects/thumbnails/7852a18a-9388-4140-b260-6c8b97597258.png'
FROM cohorts c WHERE c.name = '12기' AND c."deletedAt" IS NULL
UNION ALL
SELECT
  c.id, ARRAY['IOS']::projects_platforms_enum[], '명언제과점', '당신의 하루에 맞는 문장을 구워드립니다, 상황과 감정에 맞는 명언을 추천해주는 큐레이션 앱', 'https://storage.googleapis.com/ddd-project/projects/thumbnails/79b26382-278b-4642-b357-7c0df38f65fc.png'
FROM cohorts c WHERE c.name = '9기' AND c."deletedAt" IS NULL
UNION ALL
SELECT
  c.id, ARRAY['IOS']::projects_platforms_enum[], 'Fridge Link', '식자재를 관리하고, 지인들과 나눔하는, 냉장고 관리 서비스!', 'https://storage.googleapis.com/ddd-project/projects/thumbnails/6b9e8402-14b0-4998-97b8-82bddcdfda64.png'
FROM cohorts c WHERE c.name = '12기' AND c."deletedAt" IS NULL;

-- 3. Project members (Figma supplied roster for: FESTIBEE (페스티비)).
WITH target AS (
  SELECT id FROM projects WHERE name = 'FESTIBEE (페스티비)' AND "deletedAt" IS NULL ORDER BY id DESC LIMIT 1
)
INSERT INTO project_members ("projectId", name, part)
SELECT target.id, m.name, m.part FROM target CROSS JOIN (VALUES
  ('최현희', 'PM'),
  ('이윤경', 'DESIGN'),
  ('이무성', 'WEB'),
  ('정원석', 'WEB'),
  ('이준석', 'SERVER')
) AS m(name, part);

-- 4. Blog posts (verified externalUrl only — Figma placeholders skipped).
INSERT INTO blog_posts (title, excerpt, thumbnail, "externalUrl") VALUES
  ('픽셀을 넘어 공간으로: AI 시대, 디자이너가 XR에 주목해야 하는 이유', '오늘은 요즘 디자이너들 사이에서 가장 뜨거운 화두인 ''AI'', 그리고 그 너머의 ''Next Generation''에 대해 이야기해 보려 합니다.', 'https://storage.googleapis.com/ddd-project/blogs/thumbnails/3b605e5b-0655-4460-9975-5d4a547bd935.png', 'https://dynamic-ddd.tistory.com/5');

-- 5. Post-insert assertions (each must return TRUE).
DO $$ BEGIN IF (SELECT count(*) FROM cohorts WHERE name IN ('9기', '11기', '12기') AND status = 'CLOSED' AND "deletedAt" IS NULL) <> 3
  THEN RAISE EXCEPTION 'assertion failed: expected 3 CLOSED cohorts'; END IF; END $$;
DO $$ BEGIN IF (SELECT count(*) FROM projects WHERE name IN ('FESTIBEE (페스티비)', 'GROWIT (그로잇)', 'MOYORAK (모여락)', '엠쿵', 'POLABO', 'MOZIP', 'Pregen', '명언제과점', 'Fridge Link') AND "deletedAt" IS NULL) <> 9
  THEN RAISE EXCEPTION 'assertion failed: expected 9 projects'; END IF; END $$;
DO $$ BEGIN IF (SELECT count(*) FROM project_members m JOIN projects p ON p.id = m."projectId" WHERE p.name IN ('FESTIBEE (페스티비)', 'GROWIT (그로잇)', 'MOYORAK (모여락)', '엠쿵', 'POLABO', 'MOZIP', 'Pregen', '명언제과점', 'Fridge Link')) <> 5
  THEN RAISE EXCEPTION 'assertion failed: expected 5 project_members'; END IF; END $$;
DO $$ BEGIN IF (SELECT count(*) FROM blog_posts WHERE title IN ('픽셀을 넘어 공간으로: AI 시대, 디자이너가 XR에 주목해야 하는 이유') AND "deletedAt" IS NULL) <> 1
  THEN RAISE EXCEPTION 'assertion failed: expected 1 blog_posts'; END IF; END $$;

-- Inspect before COMMIT:
-- SELECT id, name, status FROM cohorts WHERE name IN ('9기', '11기', '12기');
-- SELECT p.id, p.name, c.name AS cohort, p.platforms, p."thumbnailUrl" FROM projects p JOIN cohorts c ON c.id = p."cohortId" ORDER BY p.id DESC LIMIT 12;
-- SELECT m.name, m.part FROM project_members m JOIN projects p ON p.id = m."projectId" WHERE p.name LIKE 'FESTIBEE%';
-- SELECT id, title, "externalUrl" FROM blog_posts ORDER BY id DESC LIMIT 5;

-- 트랜잭션은 열린 채로 끝난다. 위 검사 결과를 확인한 뒤 아래 한 줄을
-- 직접 실행해 확정하거나 되돌린다. 파일 안에 COMMIT 을 두면 전체 실행이
-- 곧 운영 DB 확정이 되어 검사 단계가 무의미해진다.
--   COMMIT;    -- 검사 결과가 기대와 같을 때
--   ROLLBACK;  -- 그 외 전부
